### ISSUE TITLE
Aircraft endpoint CircleCI test errors

### ISSUE THREAD

**Issue by valentinoli** [apis-is/apis#481]
Hey all. I've been trying to get this [pull request](https://github.com/apis-is/apis/pull/480) to pass the integration tests without any luck... Keep getting the following errors even though the endpoint works perfectly locally. Any ideas what might be causing the refusal of samgongustofa.is to respond? Both errors are due to this.
```sh
  1) aircraft
       correct-fields
         should return an array of objects containing correct fields:
     Uncaught AssertionError: Does not contain a 'results' field
      at assertResults (lib/test_helpers.js:7:3)
      at Request._callback (lib/test_helpers.js:59:5)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)

  2) aircraft
       aircraft-not-found
         should return a 404 when an aircraft is not found:

      Uncaught AssertionError: 'www.samgongustofa.is refuses to respond or give back data' === 'No aircraft found with the query loftur'
      + expected - actual

      -www.samgongustofa.is refuses to respond or give back data
      +No aircraft found with the query loftur
```

**Comment by valentinoli** [comment]
#480

**Comment by MiniGod** [comment]
Please keep conversation in the pull request #480.

**Comment by valentinoli** [comment]
Will do next time 👍
